- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resgrp: Lectoraat
    vm_name: myVM
    vm_storage: mystore1111
    vm_nsg: myNetworkSecurityGroup
    vm_vnet: myVnet
    location: eastus
    ssh_key: "{{ lookup('file', '.azure/ssh_keys/id_rsa.pub') }}"
  tasks:
  # - name: Create resource group
  #   azure_rm_resourcegroup:
  #     name: '{{ resgrp }}'
  #     location: westeurope
  - name: Create storage account
    azure_rm_storageaccount: 
      resource_group: '{{ resgrp }}'
      name: '{{ vm_storage }}'
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: '{{ resgrp }}'
      name: '{{ vm_vnet }}'
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: '{{ resgrp }}'
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: '{{ vm_vnet }}'
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: '{{ resgrp }}'
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: '{{ resgrp }}'
      name: '{{ vm_nsg }}'
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: '{{ resgrp }}'
      name: myNIC
      virtual_network: '{{ vm_vnet }}'
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: '{{ vm_nsg }}'
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: '{{ resgrp }}'
      name: '{{ vm_name }}'
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      network_interfaces: myNIC
      storage_account_name: '{{ vm_storage }}'
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest